### ISSUE TITLE
Install Failed - invalid value for attribute Version

### ISSUE THREAD

**Issue by FuJa0815** [circuitdiagram/circuitdiagram-vscode#1]
I downloaded various versions of the Visual Studio Code-Extenstion, but every time I tried to install it, it failed with the error
> Element 'Identity' has invalid value for attribute 'Version'

Here is the Install Log:
[dd_VSIXInstaller_20200403123031_26c8.log](https://github.com/circuitdiagram/circuitdiagram-vscode/files/4426611/dd_VSIXInstaller_20200403123031_26c8.log)

**Comment by SamuelFisher** [comment]
How are you trying to install it - from the drop-down menu in VS Code or by double clicking on the VSIX file?

You need to click on the "Install from VSIX..." option inside VS Code. There are [instructions here](https://www.circuit-diagram.org/news/2018/05/visual-studio-code-extension) for how to do this.

**Comment by FuJa0815** [comment]
I tried double clicking the file

**Comment by SamuelFisher** [comment]
I've added instructions for this to the readme.
